replicaCount: 1

image:
  repository: ghcr.io/matanbaruch/configmap-rs-operator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Operator specific configuration
config:
  # List of namespace regex patterns to match (empty means all namespaces)
  namespaceRegex: []
  # Example:
  # namespaceRegex:
  #   - "^default$"
  #   - "^app-.*"
  
  # Enable dry-run mode (only log what would be done)
  dryRun: false
  
  # Enable debug logging
  debug: false
  
  # Enable trace logging (more verbose than debug)
  trace: false

# Leader election settings
leaderElection:
  enabled: true

# Metrics configuration
metrics:
  enabled: true
  port: 8080
  secure: true

# Health probe configuration
healthProbe:
  port: 8081